@startuml

title __INTERFACES's Class Diagram__\n

  namespace com.example.androidximalayafm {
    namespace interfaces {
      interface com.example.androidximalayafm.interfaces.IAlbumDetailPresenter {
          {abstract} + getAlbumDetail()
          {abstract} + loadMore()
          {abstract} + pull2RefreshMore()
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace interfaces {
      interface com.example.androidximalayafm.interfaces.IAlbumDetailViewCallback {
          {abstract} + onAlbumLoaded()
          {abstract} + onDetailListLoaded()
          {abstract} + onNetworkError()
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace interfaces {
      interface com.example.androidximalayafm.interfaces.IPlayerCallback {
          {abstract} + onAdFinished()
          {abstract} + onAdLoading()
          {abstract} + onListLoaded()
          {abstract} + onNextPlay()
          {abstract} + onPlayError()
          {abstract} + onPlayModeChange()
          {abstract} + onPlayPause()
          {abstract} + onPlayStart()
          {abstract} + onPlayStop()
          {abstract} + onPrePlay()
          {abstract} + onProgressChange()
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace interfaces {
      interface com.example.androidximalayafm.interfaces.IPlayerPresenter {
          {abstract} + getPlayList()
          {abstract} + isPlay()
          {abstract} + pause()
          {abstract} + play()
          {abstract} + playByIndex()
          {abstract} + playNext()
          {abstract} + playPre()
          {abstract} + seekTo()
          {abstract} + stop()
          {abstract} + switchPlayMode()
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace interfaces {
      interface com.example.androidximalayafm.interfaces.IRecommendPresenter {
          {abstract} + getRecommendList()
          {abstract} + loadMore()
          {abstract} + pull2RefreshMore()
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace interfaces {
      interface com.example.androidximalayafm.interfaces.IRecommendViewCallback {
          {abstract} + onEmpty()
          {abstract} + onLoading()
          {abstract} + onNetworkError()
          {abstract} + onRecommendListLoaded()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
