@startuml

title __PRESENTERS's Class Diagram__\n

  namespace com.example.androidximalayafm {
    namespace presenters {
      class com.example.androidximalayafm.presenters.AlbumDetailPresenter {
          {static} - TAG : String
          - mCallbacks : List<IAlbumDetailViewCallback>
          - mTargetAlbum : Album
          {static} - sInstance : AlbumDetailPresenter
          + getAlbumDetail()
          {static} + getInstance()
          + loadMore()
          + pull2RefreshMore()
          + registerViewCallback()
          + setTargetAlbum()
          + unRegisterViewCallback()
          - AlbumDetailPresenter()
          - handlerAlbumDetailResult()
          - handlerError()
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace presenters {
      class com.example.androidximalayafm.presenters.PlayerPresenter {
          {static} - TAG : String
          - isPlayListSet : boolean
          - mIPlayerCallbacks : List<IPlayerCallback>
          - mXmPlayerManager : XmPlayerManager
          {static} + getInstance()
          + getPlayList()
          + isPlay()
          + onAdsStartBuffering()
          + onAdsStopBuffering()
          + onBufferProgress()
          + onBufferingStart()
          + onBufferingStop()
          + onCompletePlayAds()
          + onError()
          + onError()
          + onGetAdsInfo()
          + onPlayPause()
          + onPlayProgress()
          + onPlayStart()
          + onPlayStop()
          + onSoundPlayComplete()
          + onSoundPrepared()
          + onSoundSwitch()
          + onStartGetAdsInfo()
          + onStartPlayAds()
          + pause()
          + play()
          + playByIndex()
          + playNext()
          + playPre()
          + registerViewCallback()
          + seekTo()
          + setPlayList()
          + stop()
          + switchPlayMode()
          + unRegisterViewCallback()
          - PlayerPresenter()
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace presenters {
      class com.example.androidximalayafm.presenters.PlayerPresenter.PlayPresenterHolder {
          {static} - INSTANCE : PlayerPresenter
      }
    }
  }
  

  namespace com.example.androidximalayafm {
    namespace presenters {
      class com.example.androidximalayafm.presenters.RecommendPresenter {
          {static} - TAG : String
          - mCallbacks : List<IRecommendViewCallback>
          {static} - sInstance : RecommendPresenter
          {static} + getInstance()
          + getRecommendList()
          + loadMore()
          + pull2RefreshMore()
          + registerViewCallback()
          + unRegisterViewCallback()
          - RecommendPresenter()
          - handlerError()
          - handlerRecommendResult()
          - updateLoading()
      }
    }
  }
  

  com.example.androidximalayafm.presenters.AlbumDetailPresenter .up.|> com.example.androidximalayafm.interfaces.IAlbumDetailPresenter
  com.example.androidximalayafm.presenters.PlayerPresenter .up.|> com.example.androidximalayafm.interfaces.IPlayerPresenter
  com.example.androidximalayafm.presenters.PlayerPresenter .up.|> com.ximalaya.ting.android.opensdk.player.advertis.IXmAdsStatusListener
  com.example.androidximalayafm.presenters.PlayerPresenter .up.|> com.ximalaya.ting.android.opensdk.player.service.IXmPlayerStatusListener
  com.example.androidximalayafm.presenters.PlayerPresenter +-down- com.example.androidximalayafm.presenters.PlayerPresenter.PlayPresenterHolder
  com.example.androidximalayafm.presenters.RecommendPresenter .up.|> com.example.androidximalayafm.interfaces.IRecommendPresenter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
